title: How to Align Memory
author:
  name: Luna Meier
  email: lunalovecraft@gmail.com
  github: https://github.com/LunaLovecraft
description: A tutorial on how to create aligned memory in C++, using declspec(align()), _aligned_malloc(), and aligning memory from scratch.
language: C++
tags:
  - C++
  - Optimization
extra_resources:
  - https://msdn.microsoft.com/library/83ythb65.aspx
  - https://msdn.microsoft.com/en-us/library/8z34s9c6.aspx
connections:
